CREATE TABLE closeout_sessions (id VARCHAR(80) PRIMARY KEY, branch VARCHAR(180) NOT NULL, register_name VARCHAR(100) NOT NULL, expected_cash DECIMAL(12,2) NOT NULL, counted_cash DECIMAL(12,2) NOT NULL, variance DECIMAL(12,2) NOT NULL, status VARCHAR(30) NOT NULL, opened_at TIMESTAMP NOT NULL);
CREATE TABLE closeout_adjustments (id VARCHAR(80) PRIMARY KEY, session_id VARCHAR(80) NOT NULL, reason VARCHAR(400) NOT NULL, amount DECIMAL(12,2) NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE closeout_audits (id VARCHAR(80) PRIMARY KEY, session_id VARCHAR(80) NOT NULL, actor VARCHAR(140) NOT NULL, role VARCHAR(80) NOT NULL, action VARCHAR(100) NOT NULL, detail VARCHAR(400) NOT NULL, created_at TIMESTAMP NOT NULL);

