class DomainError extends Error { constructor(code, message) { super(message); this.code = code; } }
class Store {
  constructor() { this.reset(); }
  reset() { this.sequence = 0; this.sessions = []; this.adjustments = []; this.audits = []; }
  id(prefix) { this.sequence += 1; return `${prefix}-${String(this.sequence).padStart(4, '0')}`; }
  now() { return new Date().toISOString(); }
  text(value, label, max = 240) { if (typeof value !== 'string' || !value.trim()) throw new DomainError('VALIDATION', `${label} is required`); if (value.trim().length > max) throw new DomainError('VALIDATION', `${label} exceeds ${max} characters`); return value.trim(); }
  role(actor, allowed) { if (!actor || !allowed.includes(actor.role)) throw new DomainError('FORBIDDEN', 'This role cannot perform the requested action'); }
  session(id) { const value = this.sessions.find(item => item.id === id); if (!value) throw new DomainError('NOT_FOUND', `Closeout ${id} was not found`); return value; }
  audit(sessionId, actor, action, detail) { this.audits.unshift({ id: this.id('audit'), sessionId, actor: actor.name, role: actor.role, action, detail, at: this.now() }); }
  open(actor, payload) { this.role(actor, ['cashier']); const branch = this.text(payload.branch, 'Branch'); const register = this.text(payload.register, 'Register'); const expected = Number(payload.expected); const counted = Number(payload.counted); if (!Number.isFinite(expected) || expected < 0 || !Number.isFinite(counted) || counted < 0) throw new DomainError('VALIDATION', 'Expected and counted cash must be nonnegative amounts'); if (this.sessions.some(item => item.branch.toLowerCase() === branch.toLowerCase() && item.register.toLowerCase() === register.toLowerCase() && item.status === 'open')) throw new DomainError('CONFLICT', 'An open closeout already exists for this branch register'); const session = { id: this.id('closeout'), branch, register, expected, counted, variance: Number((counted - expected).toFixed(2)), status: 'open', openedAt: this.now(), reviewedBy: null }; this.sessions.push(session); this.audit(session.id, actor, 'closeout.opened', `Expected ${expected.toFixed(2)}, counted ${counted.toFixed(2)}`); return session; }
  addAdjustment(actor, id, payload) { this.role(actor, ['cashier']); const session = this.session(id); if (session.status !== 'open') throw new DomainError('CONFLICT', 'Adjustments require an open closeout'); const reason = this.text(payload.reason, 'Adjustment reason', 400); const amount = Number(payload.amount); if (!Number.isFinite(amount) || amount === 0) throw new DomainError('VALIDATION', 'Adjustment amount must be a nonzero number'); const adjustment = { id: this.id('adjustment'), sessionId: id, reason, amount, createdAt: this.now() }; this.adjustments.push(adjustment); session.variance = Number((session.variance + amount).toFixed(2)); this.audit(id, actor, 'adjustment.recorded', `${reason}: ${amount.toFixed(2)}`); return adjustment; }
  submit(actor, id) { this.role(actor, ['cashier']); const session = this.session(id); if (session.status !== 'open') throw new DomainError('CONFLICT', 'Only open closeouts can be submitted'); session.status = 'submitted'; this.audit(id, actor, 'closeout.submitted', `Submitted with variance ${session.variance.toFixed(2)}`); return session; }
  approve(actor, id, payload) { this.role(actor, ['branch-manager']); const session = this.session(id); if (session.status !== 'submitted') throw new DomainError('CONFLICT', 'Only submitted closeouts can be approved'); const note = this.text(payload.note, 'Manager note', 400); if (Math.abs(session.variance) > 100 && !note.toLowerCase().includes('investigated')) throw new DomainError('VALIDATION', 'Material variance approval requires an investigated note'); session.status = 'approved'; session.reviewedBy = actor.name; this.audit(id, actor, 'closeout.approved', note); return session; }
  snapshot(actor) { this.role(actor, ['cashier', 'branch-manager', 'finance-auditor']); return { sessions: this.sessions, adjustments: this.adjustments, audits: this.audits, metrics: { open: this.sessions.filter(item => item.status === 'open').length, submitted: this.sessions.filter(item => item.status === 'submitted').length, approved: this.sessions.filter(item => item.status === 'approved').length } }; }
}
module.exports = { DomainError, Store };

